# Generated by Django 4.1.3 on 2022-11-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fullname', models.CharField(max_length=100)),
                ('user_username', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_city', models.CharField(max_length=100)),
                ('user_state', models.CharField(max_length=100)),
                ('user_image', models.ImageField(upload_to='images/user')),
                ('user_bgimage', models.ImageField(upload_to='images/user')),
                ('user_status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_desc', models.TextField()),
                ('feed_rating', models.CharField(default='0', max_length=100)),
                ('feedback_sentiment', models.CharField(max_length=50)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to='userapp.user')),
            ],
            options={
                'db_table': 'feedback_details',
            },
        ),
    ]
